name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
    - name: Install Dependencies
      run: npm i
    - name: Build
      run: npm run build
    - name: Test
      run: npm run cover
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage/clover.xml
      if: github.event_name == 'push'
      continue-on-error: true
